app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$setInputs(speciesInput = "Merluccius ")
app$setInputs(speciesInput = "Merluccius mer")
app$setInputs(speciesInput = "Merluccius merlucc")
app$setInputs(speciesInput = "Merluccius merluccius")
app$setInputs(addSpecies = "click", wait_=FALSE, values_=FALSE)
app$setInputs(getData = "click", wait_=FALSE, values_=FALSE)
app$snapshot()
